<?php

namespace AppBundle\Repository;

/**
 * carreraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carreraRepository extends \Doctrine\ORM\EntityRepository
{
}
