<?php

namespace AppBundle\Repository;

/**
 * conceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conceptoRepository extends \Doctrine\ORM\EntityRepository
{
}
