<?php

namespace AppBundle\Repository;

/**
 * distritoescolarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class distritoescolarRepository extends \Doctrine\ORM\EntityRepository
{
}
