<?php

namespace AppBundle\Repository;

/**
 * estadosalumnosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class estadosalumnosRepository extends \Doctrine\ORM\EntityRepository
{
}
