<?php

namespace AppBundle\Repository;

/**
 * niveltipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class niveltipoRepository extends \Doctrine\ORM\EntityRepository
{
}
