<?php

namespace AppBundle\Repository;

/**
 * organizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class organizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
