<?php

namespace AppBundle\Repository;

/**
 * paisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paisRepository extends \Doctrine\ORM\EntityRepository
{
}
