<?php

namespace AppBundle\Repository;

/**
 * provinciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class provinciaRepository extends \Doctrine\ORM\EntityRepository
{
}
