<?php

namespace AppBundle\Repository;

/**
 * sexoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sexoRepository extends \Doctrine\ORM\EntityRepository
{
}
