<?php

namespace AppBundle\Repository;

/**
 * tipoivaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipoivaRepository extends \Doctrine\ORM\EntityRepository
{
}
