<?php

namespace AppBundle\Repository;

/**
 * tipodocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipodocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
