<?php

namespace AppBundle\Repository;

/**
 * usuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuariotRepository extends \Doctrine\ORM\EntityRepository
{
}
